### ISSUE TITLE
Add support for second-level menus in navigation

### ISSUE THREAD

**Issue by paulgibbs** [CouscousPHP/Template-Light#5]
Do you have any interest in a PR that adds support for second-level menus in the navigation menu?
I've chosen to implement the second-level menu as a separate horizontal menu at the top of the page content area for simplicity (to avoid having to figure out some kind of nested/dropdown for the existing menu, whose buttons are pretty large).

Pic: http://i.imgur.com/hCUo9wl.png

**Comment by mnapoli** [comment]
Sorry for not answering sooner, I don't think it would make sense to change this template:
- it's already used and would change the appearance of published websites next time they are regenerated
- it's meant to be a "simple" theme

You are welcome to publish you theme in your own repository though, then it can be added to the list: http://couscous.io/templates.html
