### ISSUE TITLE
Navigation section does not scroll

### ISSUE THREAD

**Issue by billstar** [CouscousPHP/Template-Light#7]
When the navigation section contains enough menu items to exceed the height of the window, the additional items are clipped rather than scrolling. It's hard for me to think of a site design where this would be the desired behavior. 

This theme seems to be partially based on the Bootstrap V4 dashboard design: https://v4-alpha.getbootstrap.com/examples/dashboard/ and that template does permit for the navigation section to be scrolled.

Would it be possible to update the template to scroll the contents?

**Comment by mnapoli** [comment]
Thank you for the issue, if you find a way to make it work without breaking backward compatibility (i.e. not changing the appearance of the website when the navigation fits on the screen) feel free to open a pull request. In the meantime I'll be closing this issue, see https://github.com/CouscousPHP/Template-Dark/pull/5 for more explanation.
